import { useEffect, useMemo, useState } from 'react'

type Lang = 'en' | 'zh'
type Screen = 'home' | 'quiz' | 'loading' | 'result'
type Question = { prompt: string; a: string; b: string }
type Character = { id: number; name: string; image: string; status: string; location: { name: string } }
type Profile = { id: number; name: string; zhName: string; target: number; zh: string; en: string }

const COUNT = 10
const bank: Record<Lang, Question[]> = {
  en: [
    ['A portal opens in your bathroom. First move?','Grab a towel.','Grab the portal gun.'],['A parasite remembers being your best friend.','Test one bad memory.','Shoot first.'],['Rick offers a glowing vial.','Make Rick drink it.','Bottoms up.'],['One escape pod, two people.','Repair the ship together.','Close the pod door.'],['A Meeseeks can fix your life.','Give one precise task.','Ask for eternal happiness.'],['The Council wants one name.','Say nothing.','Spell my friend’s name.'],['TV shows a famous version of you.','Watch and move on.','Replace them.'],['The cure may add tentacles.','Read the label.','Tentacles sound useful.'],['Mr. Poopybutthole suspects your friend.','Verify first.','Trust him immediately.'],['Erase one disastrous adventure.','Erase the harm.','Erase my embarrassment.'],['A button says DO NOT PRESS.','Walk away.','Obviously press it.'],['A civilization powers your car.','Set them free.','Free electricity!'],['You meet a better version of yourself.','Ask for advice.','There can be only one.'],['The Devil offers cursed cool shoes.','Check the curse.','Worth it.'],['Birdperson’s wedding may be a trap.','Go, park by the exit.','Send a gift card.'],['You wake inside a simulation.','Find the glitch.','Wait for someone else to panic.'],['An alien calls you Mom.','Call animal control.','Keep the weird child.'],['The purge starts; your friend is unarmed.','Share my spare.','They can carry snacks.'],['Your clone keeps browser history.','No clone.','Delete one folder and proceed.'],['Home or free-pizza universe?','Go home.','Pizza dimension!'],
  ].map(([prompt,a,b])=>({prompt,a,b})),
  zh: [
    ['马桶上突然开了个传送门。第一反应？','先裹毛巾，社死也是死。','抄起传送枪，裤子不重要。'],['寄生虫拥有你和死党的全部回忆。','先问一段黑历史。','先崩了再说。'],['Rick 递来一管发光液体。','让 Rick 先干为敬。','喝不死，大概。'],['逃生舱只有一个座。','一起修飞船。','关门，友情到站。'],['Meeseeks 能解决你的人生问题。','只给一个小任务。','让我永远快乐。'],['Rick 委员会要你报一个名字。','闭嘴，朋友不能卖。','把朋友资料全交了。'],['电视播到已经成名的平行宇宙自己。','看完就关，知足。','过去顶替自己。'],['解药副作用可能长触手。','先看完说明书。','触手挺实用，扎。'],['屎屁屁先生说朋友是寄生虫。','先找不快乐的回忆。','直接相信屎屁屁先生。'],['能删除一次灾难级冒险。','删掉伤害无辜的那次。','删掉我出丑的那次。'],['按钮写着“千万别按”。','拿椅子压住它。','写这么大，不按不给面子。'],['汽车电池里住着微型文明。','告诉真相，放人。','他们发电，我开车。'],['遇见每次都选对的平行宇宙自己。','赶紧取经。','世界不需要两个我。'],['恶魔送你一双受诅咒的帅鞋。','先问怎么诅咒。','帅都帅了，闹鬼算什么。'],['鸟人婚礼八成是陷阱。','去，但车头朝出口。','不去，随个红包。'],['你在模拟世界里醒来。','找系统漏洞。','等别人先崩溃。'],['抱脸虫一样的外星生物叫你妈。','联系银河动物中心。','来都来了，先养两天。'],['净化之夜开始，朋友没武器。','把备用武器给 TA。','让 TA 帮我拿零食。'],['克隆体会继承浏览器记录。','坚决不克隆。','删个文件夹就开机。'],['回家还是去披萨永久免费的宇宙？','回家，免费最贵。','披萨宇宙走起。'],
  ].map(([prompt,a,b])=>({prompt,a,b})),
}

const profiles: Profile[] = [
  {id:1,name:'Rick Sanchez',zhName:'瑞克·桑切斯',target:92,zh:'聪明、疯狂、对权威过敏。别人还在理解规则，你已经准备把规则炸了。',en:'Brilliant, reckless, and allergic to authority. You would rather blow up the rules.'},
  {id:118,name:'Evil Morty',zhName:'邪恶莫蒂',target:78,zh:'冷静、会布局、早就受够别人定的规则。你不是逃跑，是在重写游戏。',en:'Patient, strategic, and completely done with everyone else’s rules.'},
  {id:3,name:'Summer Smith',zhName:'桑美·史密斯',target:65,zh:'反应快、胆子大、社交杀伤力拉满。别人尖叫时，你已经把飞船开走了。',en:'Fast, fearless, socially lethal, and much more capable than expected.'},
  {id:4,name:'Beth Smith',zhName:'贝丝·史密斯',target:52,zh:'能力强、主意正、情绪结构复杂。再糟糕一点，你就该去当太空 Beth。',en:'Competent, complicated, and one bad day away from becoming Space Beth.'},
  {id:2,name:'Morty Smith',zhName:'莫蒂·史密斯',target:38,zh:'表面慌得一批，心里还有底线。真要命时，你比自己想得更勇。',en:'Nervous outside, stubbornly decent inside, and braver than you think.'},
  {id:47,name:'Birdperson',zhName:'鸟人',target:25,zh:'话少、靠谱、认定一边绝不回头。你不抢戏，但一般能活到片尾。',en:'Quiet, loyal, and terrifyingly committed once you choose a side.'},
  {id:5,name:'Jerry Smith',zhName:'杰瑞·史密斯',target:10,zh:'靠谨慎、运气和被所有人低估活到最后。这也是一种实力。',en:'Survival through caution, luck, and being underestimated by everyone.'},
]

const text = {
  en:{brand:'WHO ARE YOU IN R&M?',hero:['WHICH R&M','CHARACTER ARE YOU?'],body:['Answer 10 random multiverse dilemmas.','We analyze your choices and find your closest character.','Get a character card and match percentage.'],start:'START THE TEST',question:'DILEMMA',analyzing:'SCANNING YOUR MULTIVERSE PERSONALITY',loading:['SEARCHING EVERY','KNOWN DIMENSION…'],you:'YOU ARE',match:'MATCH',result:'MULTIVERSE IDENTITY RESULT',again:'SCAN AGAIN',download:'DOWNLOAD CHARACTER CARD',copy:'COPY RESULT',copied:'COPIED',desc:'20 QUESTIONS · 7 CHARACTERS · ONE MATCH',chaos:'CHAOS SIGNATURE',status:'STATUS',location:'LAST KNOWN LOCATION',alive:'Alive',dead:'Dead',unknown:'Unknown'},
  zh:{brand:'你是 R&M 里的谁？',hero:['测测你是 R&M','里的谁。'],body:['每次随机抽 10 道多元宇宙怪题。','根据你的选择匹配最像的角色。','最后生成角色卡片和匹配度百分比。'],start:'开始角色测试',question:'脑洞题',analyzing:'正在扫描你的多元宇宙人格',loading:['正在翻遍所有宇宙','寻找另一个你……'],you:'你是',match:'匹配度',result:'多元宇宙人格鉴定结果',again:'再测一次',download:'保存角色卡片 PNG',copy:'复制结果',copied:'已复制',desc:'20 道题库 · 7 个角色 · 1 个匹配结果',chaos:'混乱人格指数',status:'角色状态',location:'最后出现地点',alive:'存活',dead:'已死亡',unknown:'生死不明'},
} as const

function pick(){const ids=[...Array(bank.en.length).keys()];for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}return ids.slice(0,COUNT)}
function Arrow(){return <svg viewBox="0 0 28 16" aria-hidden="true"><path d="M1 8h24M18 1l7 7-7 7" fill="none" stroke="currentColor" strokeWidth="2.5"/></svg>}
type Text = (typeof text)[Lang]
type ResultData = {character:Character;profile:Profile;match:number;score:number}
const zhLocations:Record<number,string>={1:'替代维度地球',2:'替代维度地球',3:'替代维度地球',4:'替代维度地球',5:'替代维度地球',47:'鸟人星球',118:'中央有限曲线之外'}
function displayName(data:ResultData,lang:Lang){return lang==='zh'?`${data.profile.zhName} / ${data.character.name}`:data.character.name}
function displayStatus(status:string,lang:Lang,t:Text){if(lang==='en')return status;if(status==='Alive')return t.alive;if(status==='Dead')return t.dead;return t.unknown}
function displayLocation(data:ResultData,lang:Lang){return lang==='zh'?(zhLocations[data.character.id]||'未知维度'):data.character.location.name}
async function loadCardImage(src:string){const response=await fetch(src);if(!response.ok)throw new Error('image unavailable');const objectUrl=URL.createObjectURL(await response.blob());return new Promise<HTMLImageElement>((resolve,reject)=>{const image=new Image();image.onload=()=>{URL.revokeObjectURL(objectUrl);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(objectUrl);reject(new Error('image unavailable'))};image.src=objectUrl})}
async function createCardUrl(data:ResultData,lang:Lang,t:Text){const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const c=canvas.getContext('2d')!;c.fillStyle='#d7d8c8';c.fillRect(0,0,1080,1350);c.strokeStyle='#11130f';c.lineWidth=6;c.strokeRect(28,28,1024,1294);try{const image=await loadCardImage(data.character.image);c.drawImage(image,70,120,520,520)}catch{c.fillStyle='#8cff45';c.fillRect(70,120,520,520)}c.fillStyle='#ff5a24';c.fillRect(620,120,390,520);c.fillStyle='#11130f';c.font='800 48px sans-serif';c.fillText(t.match,660,230);c.font='900 142px sans-serif';c.fillText(`${data.match}%`,650,430);c.fillStyle='#11130f';c.font=lang==='zh'?'900 62px sans-serif':'900 80px sans-serif';c.fillText(displayName(data,lang),70,760);c.font='600 32px sans-serif';c.fillText(`${t.chaos}  ${data.score}%`,70,860);c.fillText(`${t.status}  ${displayStatus(data.character.status,lang,t)}`,70,930);c.fillText(`${t.location}  ${displayLocation(data,lang)}`,70,1000);c.font='500 28px sans-serif';const description=data.profile[lang];c.fillText(description.slice(0,30),70,1100);if(description.length>30)c.fillText(description.slice(30,60),70,1145);c.font='900 46px sans-serif';c.fillText(lang==='zh'?'你是 R&M 里的谁？':'WHO ARE YOU IN R&M?',70,1260);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('render failed')),'image/png'));return URL.createObjectURL(blob)}

export default function CharacterQuizApp(){
  const [lang,setLang]=useState<Lang>(()=>{const saved=localStorage.getItem('wdf-language-preference');if(saved==='zh'||saved==='en')return saved;return navigator.language.toLowerCase().startsWith('zh')?'zh':'en'})
  const [screen,setScreen]=useState<Screen>('home');const [result,setResult]=useState<ResultData|null>(null);const [copied,setCopied]=useState(false);const t=text[lang]
  useEffect(()=>{document.documentElement.lang=lang==='zh'?'zh-CN':'en';document.title=lang==='zh'?'测测你是《瑞克和莫蒂》里的谁':'Which Rick and Morty Character Are You?';window.scrollTo(0,0)},[lang,screen])
  function toggle(){setLang(v=>{const n=v==='en'?'zh':'en';localStorage.setItem('wdf-language-preference',n);return n})}
  async function finish(ids:number[],answers:number[]){setScreen('loading');const score=Math.round(answers.reduce((s,a,i)=>s+(a?7+(ids[i]%4):1+(ids[i]%3)),0)/answers.length*10);const ranked=profiles.map(p=>({p,d:Math.abs(p.target-score)})).sort((a,b)=>a.d-b.d)[0];let character:Character={id:ranked.p.id,name:ranked.p.name,image:`https://rickandmortyapi.com/api/character/avatar/${ranked.p.id}.jpeg`,status:'Unknown',location:{name:'Unknown Dimension'}};try{const r=await fetch(`https://rickandmortyapi.com/api/character/${ranked.p.id}`);if(r.ok)character=await r.json()}catch{}const match=Math.max(72,Math.min(97,Math.round(98-ranked.d*.65)));setTimeout(()=>{setResult({character,profile:ranked.p,match,score});setScreen('result')},1300)}
  async function copy(){if(!result)return;await navigator.clipboard.writeText(`${lang==='zh'?'我在《瑞克和莫蒂》里最像':'My Rick and Morty match is'} ${result.character.name} — ${result.match}%`);setCopied(true);setTimeout(()=>setCopied(false),1500)}
  return <div className="app-shell" data-language={lang}><header className="site-header"><button className="wordmark persona-wordmark" onClick={()=>setScreen('home')}>{t.brand}</button><div className="header-code">R&M-20 // PERSONALITY SCANNER<br/>MULTIVERSE IDENTITY TEST</div><div className="header-actions"><span className="daily-dot"/><span>SCAN 20-C</span><button className="language-toggle" onClick={toggle}>{lang==='en'?'中':'EN'}</button></div></header><aside className="side-rail"><div className="globe-mark">◎</div><strong>20-C</strong><span className="barcode"/><dl><dt>BANK</dt><dd>20</dd><dt>POOL</dt><dd>7</dd><dt>QUESTIONS</dt><dd>10</dd><dt>MATCH</dt><dd>{screen==='result'?'FOUND':'PENDING'}</dd></dl></aside>{screen==='home'&&<Home t={t} start={()=>setScreen('quiz')}/>} {screen==='quiz'&&<Quiz lang={lang} t={t} done={finish}/>} {screen==='loading'&&<main className="loading-screen"><img src="/portal-machine.png" alt=""/><p>{t.analyzing}</p><h1>{t.loading[0]}<br/>{t.loading[1]}</h1><div className="loading-bar"><span/></div></main>} {screen==='result'&&result&&<Result t={t} lang={lang} data={result} copied={copied} copy={copy} reset={()=>{setResult(null);setScreen('home')}}/>}</div>
}

function Home({t,start}:{t:(typeof text)[Lang];start:()=>void}){return <main className="home-screen"><section className="hero-copy"><h1>{t.hero[0]}<br/><span>{t.hero[1]}</span></h1><p>{t.body.map(x=><span key={x}>{x}<br/></span>)}</p><button className="primary-button" onClick={start}>{t.start}<Arrow/></button><div className="utility-line">{t.desc}</div></section><div className="portal-stage"><img src="/portal-machine.png" alt=""/><div className="portal-status"><span>IDENTITY MATCH</span><b>??%</b><em>UNKNOWN</em></div></div><section className="process-strip"><article><b>01</b><h2>10 RANDOM<br/>QUESTIONS</h2><p>Every test pulls a fresh set.</p></article><article><b>02</b><h2>PERSONALITY<br/>ANALYSIS</h2><p>Your choices become evidence.</p></article><article><b>03</b><h2>CHARACTER<br/>CARD</h2><p>One role. One match percentage.</p></article></section></main>}
function Quiz({lang,t,done}:{lang:Lang;t:(typeof text)[Lang];done:(i:number[],a:number[])=>void}){const ids=useMemo(pick,[]);const [answers,setAnswers]=useState<number[]>([]);const q=bank[lang][ids[answers.length]];function choose(a:number){const next=[...answers,a];setAnswers(next);if(next.length===COUNT)setTimeout(()=>done(ids,next),300)}return <main className="quiz-screen"><section className="quiz-panel persona-quiz-panel"><div className="quiz-intro"><span>{t.analyzing}</span></div><div className="progress-track" style={{gridTemplateColumns:`repeat(${COUNT},1fr)`}}>{ids.map((_,i)=><span key={i} className={i<answers.length?'done':i===answers.length?'active':''}>{String(i+1).padStart(2,'0')}</span>)}</div>{q&&<div className="question-wrap" key={answers.length}><p className="question-number">{t.question} {String(answers.length+1).padStart(2,'0')} / 10</p><h1>{q.prompt}</h1><div className="answer-grid"><button onClick={()=>choose(0)}><small>A</small><span>{q.a}</span><Arrow/></button><button onClick={()=>choose(1)}><small>B</small><span>{q.b}</span><Arrow/></button></div></div>}</section><div className="quiz-portal"><img src="/portal-machine.png" alt=""/></div></main>}
function Result({t,lang,data,copied,copy,reset}:{t:Text;lang:Lang;data:ResultData;copied:boolean;copy:()=>void;reset:()=>void}){const [cardUrl,setCardUrl]=useState('');useEffect(()=>{let active=true;let url='';void createCardUrl(data,lang,t).then(value=>{url=value;if(active)setCardUrl(value)});return()=>{active=false;if(url)URL.revokeObjectURL(url)}},[data,lang,t]);return <main className="persona-result-screen"><section className="persona-card"><div className="persona-photo"><img src={data.character.image} alt={data.character.name}/><span>{t.match}<strong>{data.match}%</strong></span></div><div className="persona-copy"><p className="section-code">{t.result}</p><h1><small>{t.you}</small>{displayName(data,lang)}</h1><p className="persona-description">{data.profile[lang]}</p><div className="identity-meter"><span>{t.chaos}</span><i><b style={{width:`${data.score}%`}}/></i><strong>{data.score}%</strong></div><dl className="character-facts"><div><dt>{t.status}</dt><dd>{displayStatus(data.character.status,lang,t)}</dd></div><div><dt>{t.location}</dt><dd>{displayLocation(data,lang)}</dd></div></dl></div></section><div className="persona-actions"><a className="primary-button" href={cardUrl||undefined} download={`rm-${data.character.id}-${data.match}.png`} aria-disabled={!cardUrl}>{cardUrl?t.download:(lang==='zh'?'正在生成角色卡片…':'RENDERING CARD…')}<Arrow/></a><button className="utility-button" onClick={copy}>{copied?t.copied:t.copy}</button><button className="text-button" onClick={reset}>{t.again}<Arrow/></button></div></main>}
